[package]
name = "ai_chat"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.63"
ureq = { version = "2.10.1", features = ["json"] }
